### ISSUE TITLE
Algorytmy wlaczania pomp oraz duty changeover

### ISSUE THREAD

**Issue by LukaszBrzuszkiewicz** [baszczewski/cwc-issues#2]
Przetestowalem algorytmy w ostatnio podeslanej wersji, dziala to mniej wiecej tak jak powinno, funkcjonalnosc ktora nie dziala jeszcze do konca dobrze to:

-po stripowaniu aktualnie wlaczonej pompy (range1) druga pompa nie przejmuje jej roli, tzn nie wlacza sie gdy zostanie osigniety prog wlaczenia pompy range1

-w trybie ‘time based’, wlaczone/aktywne dwa zakresy, jeden wyszy od drugiego, obie pompy nieraz sie wlaczaja mimo ze zakres wlaczenia drugiej pompy nie zostal osiagniety, wydaje sie jakby pompom zostal przypisany ten sam zakres

-nazwy zakresow powinny byc Duty dla Range1 oraz Assist1, Assist2 ... dla Range2, Range3, itd

**Comment by baszczewski** [comment]
Myślę, że dobrze będzie to wspólnie przetestować. Sam tripa już miałem okazję zweryfikować według powyższego scenariusza i był w porządku. 
Najlepiej będzie jak docelową rolę pompy, będziemy pokazywali w obrębie zakładki "details". Tym sposobem będzie możliwe w każdej chwili zweryfikować nadaną rolę. 
Jeśli chodzi o nazewnictwo kolejnych ról. Wprowadzimy je wraz z zakładką ustawień zaawansowanych w obrębie zbiorników.

**Comment by LukaszBrzuszkiewicz** [comment]
Zgadza sie, uruchomie skypa na paneliku I dam znac jak juz bedzie gotowe do testow

**Comment by baszczewski** [comment]
Udostępniłem mailem nową wersję wtyczki. Etykiety w ustawieniach zaktualizowałem. Przyda się kolejna iteracja testów. W razie czego otworzymy kolejne zgłoszenie.
