### ISSUE TITLE
deklaracje dodatkowych eventow

### ISSUE THREAD

**Issue by LukaszBrzuszkiewicz** [baszczewski/cwc-issues#3]
Moglbys w wolnej chwili dodac do pliku  CWC\libs\modbus\modbus\event_log_helper.cpp ponisze deklaracje zdazen, ich sekcja znajduje sie w okolicach 14tej lini

                case 0x0012: return QObject::tr("Dry well protection APP activated");
                case 0x0013: return QObject::tr("Odour Control APP activated");
                case 0x0014: return QObject::tr("Volume Control APP activated");
                case 0x0015: return QObject::tr("Wet well clean APP activated");

**Comment by baszczewski** [comment]
W porządku. Dodałem definicję danych wpisów z dziennika zdarzeń. Równocześnie wskazałem dla nich typ: "powiadomienia".
